### ISSUE TITLE
Integration for Code-Server

### ISSUE THREAD

**Issue by thueske** [keesschollaart81/vscode-home-assistant#1828]
Hello,

I would like to use the extension in conjunction with the VS Code server (https://hub.docker.com/r/linuxserver/code-server).

Unfortunately the extension is not found in the store for installation. If I download the *.vsix file and try to install it, I only get the message "No servers".

Would it be possible to customize the extension for use with a remote code server?

Best regards
Tobias

**Comment by frenck** [comment]
This extension works with code server. The Home Assistant Communtiy Add-on: Code Server Studio, is actually shipping it built-in even.

**Comment by thueske** [comment]
I'm not using Home Assistant OS. I just want to start the above Docker container and install the Home Assistant VS code extension.

**Comment by frenck** [comment]
> I'm not using Home Assistant OS. I just want to start the above Docker container and install the Home Assistant VS code extension.

I was not saying you should use the add-on; I was merely mentioning it because the add-on uses code-server and this extension: showing it works.

**Comment by realjohimself** [comment]
I have this issue also. I think the addon needs to be registered at https://open-vsx.org/ since that is where the LSIO code-server gets addons from.

**Comment by frenck** [comment]
> I think the addon needs to be registered at open-vsx.org since that is where the LSIO code-server gets addons from.

That isn't needed or a requirement. You can download it from the releases page or from the vscode marketplace.

**Comment by thueske** [comment]
No @frenck. Inside vscode-server the addon is not shown. And if I download the *.vsix file and try to install it, I only get the message "No servers".

Workarounded Installation via CLI as root works (like you did it in your hass os plugin), but that's not the normal use case.

**Comment by frenck** [comment]
> Inside vscode-server the addon is not shown.

The add-on was just an example of code-server using the extension, just to indicate it works as expected. Jeez.

> And if I download the *.vsix file and try to install it, I only get the message "No servers".

Then configure those. I tried it, works for me.

>  Workarounded Installation via CLI as root works

That isn't needed and sounds like you have other issues in your setup.

> like you did it in your hass os plugin

That is not what the add-on does.

> but that's not the normal use case.

open-vsx.org isn't a normal use-case either.

**Comment by realjohimself** [comment]
As an FYI coder, code-server and other open-source implementations use open-vsx as use of the Microsoft extension store violates their Ts & Cs, so it is a fairly normal use case. As there have been 45m pulls on LSIO's code-server image it may be a decision worth reviewing.

**Comment by realjohimself** [comment]
OK. Since one-click installation in code-server is unsupported, can I request instructions on installing the .vsix please? Or is that unsupported too?

Honestly, I'm just trying to find some help getting something to work, not debate the relative merits of proprietary vs open source app stores, and having evidence that it runs without providing instructions isn't very helpful.

**Comment by amitvaria** [comment]
I can confirm that I was able to wget the latest VSIX into my host folder and then use Install from VSIX in code server. I was able to configure the extension in settings and all is working as intended.

**Comment by RoboMagus** [comment]
I stumbled across this issue when after updating my `code-server` container and some extensions could no longer be found.
@realjohimself, to answer your question on how to install the extenstion manually:
1. go to the [releases](https://github.com/keesschollaart81/vscode-home-assistant/releases) page for this plugin, and for the version you want to install, under assets find the [*.vsix file](https://github.com/keesschollaart81/vscode-home-assistant/releases/download/v1.24.0/vscode-home-assistant-1.24.0.vsix)
2. Download this file to your local machine.
3. Open your interface for `code-server` in your browser and click on the extensions link in the left sidebar.
4. Click on the 3 dots `...` at the top right of the expanded sidebar and select install from VSIX
5. In the pop-up thingy click on `show-local` to browse files on your local computer, and select the file you just downloaded.

Indeed I agree that this discussion (when reading through it) seems to be leading nowhere. So let me throw in my attempt:

@keesschollaart81 /  @frenck . I still think it would be valid request to have this extension added to open-vsx, as people will start running into this issue more. There is no other limitation of installing this plugin into `code-server` other than it not being listed in the extensions gallery that has recently been changed.

[how can I request an extension thats missing from the marketplace](https://github.com/coder/code-server/blob/main/docs/FAQ.md#how-can-i-request-an-extension-thats-missing-from-the-marketplace)

**Comment by frenck** [comment]
@RoboMagus No reason to tag people. I already gave my answers above multiple times.

**Comment by RoboMagus** [comment]
Disagree @frenk, As the maintainer of this extension has not yet been involved in this discussion this was definately worth tagging for, as action is requested in order to get this extension listed on [open VSX](https://open-vsx.org/).

The reason I tagged you in particular was to draw attention to the fact that your input on this issue was moving away from what was asked already in the 5th reply on this issue;
> I have this issue also. I think the addon needs to be registered at https://open-vsx.org/ since that is where the LSIO code-server gets addons from.


That it would be nice to have this plugin listed on the marketplace mentioned, instead of listing alternative installation methods. 

For the extension itself, nothing at all has to change; the *.vsix is fully compatible. The only issue here is not being able to install the extension in `code-server` environments of `v4.0.1` and newer.

Though to be fair, it has little to do with the 'addon' as such...

**Comment by frenck** [comment]
@RoboMagus I was referring to the tagging. In general tagging people to get answers directly out of the blue is kinda demanding and not something I appreciate.

And yes, I already gave my answers above. Sorry to hear you don't agree with them.

**Comment by ammmze** [comment]
frenck, let's try to be a little more open and listen to what the folks are saying. They are saying that the code-server no longer uses the Microsoft Marketplace for extensions because it violates the terms of service. The FAQ on codercom's code-server repo mentions this [here](https://github.com/coder/code-server/blob/10f57bac65f9aa5938df4e495da39c608fbf7798/docs/FAQ.md#why-cant-code-server-use-microsofts-extension-marketplace).

Assuming you are running this add-on and it is up-to-date, would you open your code server and go to the extensions side bar. Does it show that it is searching the "Marketplace" or "open-vsx.org"? My code server running codercom's code-server is searching open-vsx. codercom's code-server is what the hass.io addon is using.

![Screen Shot 2022-02-16 at 12 24 09 AM](https://user-images.githubusercontent.com/203336/154215974-d7ee746f-a345-4e41-994d-989e6f3b1700.png)

So now, let's take a look at the hass.io addon. It appears the installation method it uses is we have a file that lists the extensions to install. [The docker build iterates over the list and installs them from the Microsoft Marketplace](https://github.com/hassio-addons/addon-vscode/blob/main/vscode/Dockerfile#L75). So the installation method used by hass.io add-on is using the microsoft marketplace in an un-official manner and is probably technically against the Terms of Service.

**Comment by ammmze** [comment]
Publishing to open-vsx doesn't appear to be difficult. Once registered and we have a token (as described [here](https://github.com/eclipse/openvsx/wiki/Publishing-Extensions)), it looks like we can just add another step to the [workflow](https://github.com/keesschollaart81/vscode-home-assistant/blob/dev/.github/workflows/github-actions-vscode-extension.yml) using an [existing github action](https://github.com/HaaLeo/publish-vscode-extension#readme) that publishes it.

**Comment by keesschollaart81** [comment]
Unless Frenck is willing/planning to do so, I'm happy to investigate some time in what it takes to publish to open-vsx, mainly to learn about at and people seem to care ^^

Will be doing so next weekend.

**Comment by ammmze** [comment]
👍🏻  Thank you! Ultimately it is not necessarily that everyone is _wanting_ to move away from the Microsoft Marketplace. But the terms of service prohibits code-server from using it. They recently made the change so that their product no longer uses the Microsoft Marketplace, which in turn has forced people to use it (assuming they don't change from the defaults and abide by the terms of service set out by Microsoft). It's just how the world works. Things change and we sometimes we gotta go with it.

**Comment by frenck** [comment]
I think it's not needed 🤷‍♂️ 

Just adds another maintenance piece to the table, while there is already to. Of maintenance work to do.

And even if I wanted, I can't add it due to insufficient rights on this repository

**Comment by ammmze** [comment]
> I think it's not needed 🤷‍♂️

So...you're saying that the hass.io add-on is allowed to ignore the Microsoft Visual Studio Marketplace Terms of Use because you think it's not needed? [This](https://github.com/hassio-addons/addon-vscode/blob/a4585bd7f77ce29970b31308b7a49c8e059f0f3e/vscode/Dockerfile#L75) is 'using Marketplace offerings', which according to the [Terms of Use](https://cdn.vsassets.io/v/M146_20190123.39/_content/Microsoft-Visual-Studio-Marketplace-Terms-of-Use.pdf) says:
>  Marketplace Offerings are intended for use only with Visual Studio Products and Services and you may only install and use Marketplace Offerings with Visual Studio Products and Services.

**Comment by ammmze** [comment]
To be clear, i'm not saying hass.io needs to publish these. But given the shift in the community, we should probably start promoting publishing to open-vsx to the extensions we are using. Let's be team players and help out the community. Once all the hass.io add-on's are available on open-vsx, we should probably update the hass.io add-on to install from open-vsx as well.

**Comment by frenck** [comment]
> we should probably start promoting the use of open-vsx for the extensions we are using

We should promote open source, that doesn't mean open stores. Those are different things.

Also @ammmze the term "hassio" isn't used for years anymore, as it is ambiguous and not related to this project in any way.

**Comment by ammmze** [comment]
You seem to be missing the point. The code server addon that lives in the hassio-addons repository is technically violating Microsoft's terms of use by downloading from the Microsoft vs marketplace from a non-microsoft product. At some point should probably be remedied. The community is shifting to using an store/marketplace that is suitable for use outside of Microsoft products. The proposal for this vscode addon to publish to the store that highest use AND can be used by non-Microsoft products is valid and MAY be useful to the code-server addon that lives in the hassio-addons repository. You are correct it doesn't currently directly impact the hass addon, but it can be an asset in the future if the hass addon decides to abide by Microsoft's terms of use. 

In the end, the point is that this request to publish to open-vsx is valid and supports where the community is going. I don't really care whether hass abides by Microsoft's rules...I'm not using it.

Goodnight, I'm going to bed.

**Comment by frenck** [comment]
> Goodnight, I'm going to bed.

Night! 👋

**Comment by keesschollaart81** [comment]
https://open-vsx.org/extension/keesschollaart/vscode-home-assistant

I've published it. I did not test it with any of the possible clients though, I assume some of you are happy to do so. It's very likely some IDE versions / integrations might not (yet) work. If you like that IDE, feel free to drop a PR here with a fix. Fixes will, from now on, also be published to Open VSX.
