### ISSUE TITLE
Trigger Prettier YAML Formatting

### ISSUE THREAD

**Issue by Davst** [keesschollaart81/vscode-home-assistant#248]
Hi, love the extension, the main fault for me at the moment is the Home Assistant File Type blocks Prettier from cleaning my files on save. 

It'd be great if you could add an option to trigger Prettier on save etc. 

Thanks!

**Comment by keesschollaart81** [comment]
I assume you use the [Prettier Formatter for VS Code](https://github.com/prettier/prettier-vscode)? Cant you create a Home Assistant specific language configuration to do the onsave-formatting?

**Comment by GeorgeSG** [comment]
I'm having the same issue. Unfortunately, I don't think you can fix this with a custom configuration. I think the Prettier VSCode extensions asks the [prettier](https://github.com/prettier/prettier) module for supported languages and allows only the ones specified by prettier itself.

So my understanding is - in order to support Prettier for Home Assistant, either prettier itself would have to know about home-assistant as a file type, or this extension will have to work without changing the yaml file association.

**Comment by awolkers** [comment]
Same issue here, simple removing the home assistant file association isn't also an option because then I loose the autocomplete functionality for sensors etc.

**Comment by frenck** [comment]
We could try opening up a PR @ Prettier?

<https://github.com/prettier/prettier/blob/63984d3470cec3edbb5ce4bdf8ccb2900a49addc/src/language-yaml/index.js#L11>

I also notice Kubernetes is missing there 👼

**Comment by frenck** [comment]
Actually this is prettier well (👈  Phun intended) well documented by Prettier.

See: https://github.com/prettier/prettier-vscode/wiki/Custom-File-Extension-Configuration#custom-language-identifier


Opening a pull request @ Prettier as per documentation.

**Comment by frenck** [comment]
PR @ Prettier: <https://github.com/prettier/prettier/pull/8739>

Now we wait 🙏

**Comment by frenck** [comment]
Merged 🎉 

![image](https://user-images.githubusercontent.com/195327/87421292-fc9c5b00-c5d6-11ea-9870-cf9d93086350.png)


Part of the next Prettier release I guess. Closing the issue on this end, since this is not really solvable at the end of this extension!
