### ISSUE TITLE
Unexpected property "auth_mfa_modules"

### ISSUE THREAD

**Issue by zimgui** [keesschollaart81/vscode-home-assistant#25]
Recently VS show "Unexpected property "auth_mfa_modules" at HomeAssistant section in configuration.yaml.
Using HA 0.92.2 and your package 0.5.3

**Comment by keesschollaart81** [comment]
Thanks. Will be fixed in the next release!

**Comment by Juggels** [comment]
Hi Kees, thank you for fixing this! However, now you have set it as a mandatory value... Perhaps it can be made an optional field? Because I have a `customize:` section (which is a subsection of `homeassistant`) in almost all of my packages (see also [here](https://www.home-assistant.io/docs/configuration/packages/#customizing-entities-with-packages)), I now get an error message that the `auth_mfa_modules` field is not present in that file. This is of course as I expect it, because I only want to set that field in one of my config (package) files.

**Comment by keesschollaart81** [comment]
You're right, it's indeed optional!
