### ISSUE TITLE
Extension not working when workspace is opened via SSH FS

### ISSUE THREAD

**Issue by sagilo** [keesschollaart81/vscode-home-assistant#3]
I'm using SSH FS to load my workspace via SSH.
It looks like the extension doesn't work when the active workspace isn't local.

**Comment by ezraholm50** [comment]
Same here, don't know if sshfs is related to this issue. Though i'm using SSHFS and i cant get it to work, after setting the url and long lived token.

**Comment by keesschollaart81** [comment]
So I guess [the way I trigger the start of this extension](https://github.com/keesschollaart81/vscode-home-assistant/blob/master/package.json#L21) (via [workspaceContains](https://code.visualstudio.com/api/references/activation-events#workspaceContains):**/configuration.yaml) does not fire when on 'remote' filesystems. 

As a 'fix', I've added a onFileSystem trigger for SSH and FTP so that it also starts for all projects on remote file systems. Which seem to work... 

So I guess this is a trade off, I could have added the onLanguage:yaml but then the extension will start for a lot of unrelated projects as well. Let me know if I missed something here...

**Comment by sagilo** [comment]
@keesschollaart81 Thanks for the quick fix. I can confirm it's working. (v 0.2.1)

**Comment by ezraholm50** [comment]
I've updated to 0.2.1 but still get this after typing `entity_id:`

`Error connecting to your Home Assistant Server at https://192.168.x.x:8123, check your network or update your VS Code Settings. Error: 1`

Server settings and token are valid.
Please advise.

**Comment by sagilo** [comment]
@ezraholm50 I personally reinstalled the extension and restarted VS Code. try it.

**Comment by keesschollaart81** [comment]
Error 1 is [ERR_CANNOT_CONNECT](https://github.com/home-assistant/home-assistant-js-websocket/blob/master/lib/errors.ts) ('If the client was unable to connect to the websocket API'). Which suggest that there's something with the Host URL...?!

**Comment by ezraholm50** [comment]
Well i use the same settings for node red, url wise. Will try to reinstall just a sec.
