### ISSUE TITLE
Publish to Open VSX

### ISSUE THREAD

**Issue by exponentactivity** [keesschollaart81/vscode-home-assistant#455]
Free/libre builds of VS Code aren't allowed to use the the official extension marketplace, therefore it would be great to have this extension published on Open VSX too.

[More on this, as well as instructions to do this](https://www.gitpod.io/blog/open-vsx/)

**Comment by frenck** [comment]
We are not ready for this yet, mainly because we are currently restructuring some parts.

Furthermore, the extension is attached to the releases, alternatively can be built manually or can just be downloaded from the market place.

For example, the Visual Studio Code add-on for Home Assistant, also uses the marketplace, while still being a free/libre build.

Closing this for now.
